seed: 0
mode: human
output_path: output
exp_name: demo-jumping-sfu
dataset_path: 'data/neuman/dataset/bike'
# Use SFU jumping motion instead of custom motion from MDM
# custom_motion_path: '/home/sigma/project_avatar2_hugs/ml-hugs-NTHUavatar/data/custom_motions/jumping_motion_bike.npz'
detect_anomaly: false
debug: false
wandb: false
eval: true
bg_color: white
dataset:
  name: neuman
  seq: ["bike"]
train:
  batch_size: 1
  num_workers: 0
  num_steps: 10000
  save_ckpt_interval: 10000
  val_interval: 2000
  anim_interval: 8000
  optim_scene: true
  save_progress_images: false
  progress_save_interval: 10
human:
  name: hugs_trimlp
  ckpt: output/pretrained_models/bike/human_final.pth
  sh_degree: 0
  n_subdivision: 2
  only_rgb: false
  use_surface: false
  use_deformer: true
  init_2d: false
  disable_posedirs: true
  res_offset: false
  rotate_sh: false
  isotropic: false
  init_scale_multiplier: 0.5
  run_init: false
  estimate_delta: true
  triplane_res: 256
  optim_pose: true
  optim_betas: false
  optim_trans: true
  optim_eps_offsets: false
  activation: relu
  canon_nframes: 60
  canon_pose_type: da_pose
  knn_n_hops: 3
  lr:
    wd: 0.0
    position: 0.00016
    position_init: 0.00016
    position_final: 1.6e-06
    position_delay_mult: 0.01
    position_max_steps: 30000
    opacity: 0.05
    scaling: 0.005
    rotation: 0.001
    feature: 0.0025
    smpl_spatial: 2.0
    smpl_pose: 0.0001
    smpl_betas: 0.0001
    smpl_trans: 0.0001
    smpl_eps_offset: 0.0001
    lbs_weights: 0.0
    posedirs: 0.0
    percent_dense: 0.01
    appearance: 0.001
    geometry: 0.001
    vembed: 0.001
    deformation: 0.0001
    scale_lr_w_npoints: false
  loss:
    ssim_w: 0.2
    l1_w: 0.8
    lpips_w: 1.0
    lbs_w: 1000.0
    humansep_w: 0.0
    num_patches: 4
    patch_size: 128
    use_patches: 1
  densification_interval: 300
  opacity_reset_interval: 3000
  densify_from_iter: 1500
  densify_until_iter: 8000
  densify_grad_threshold: 0.0002
  prune_min_opacity: 0.01
  densify_extent: 2.0
  max_n_gaussians: 224288
  percent_dense: 0.01
scene:
  name: scene_gs
  ckpt: output/pretrained_models/bike/scene_final.pth
  sh_degree: 3
  add_bg_points: false
  num_bg_points: 204800
  bg_sphere_dist: 5.0
  clean_pcd: false
